### ISSUE TITLE
Linter issue: internal/errors/errors.go:61:1: exported function NewErrorf should have comment or be unexported

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-operator-gathering-conditions-service#43]
internal/errors/errors.go:61:1: exported function NewErrorf should have comment or be unexported

**Comment by tameryldz** [comment]
> internal/errors/errors.go:61:1: dışa aktarılan işlev NewErrorf yoruma sahip olmalı veya dışa aktarılmamış olmalıdır

**Comment by tameryldz** [comment]
Selam
